#!/usr/bin/with-contenv sh
##
# This script uses envsubst to render nginx templates heredoc hack to substitute env variables into static config files
##

echo "INFO: Substituting env into configuration files..."

# Nginx doesn't support env variables in config files so we will have to do this in hacky way instead
VARS='$RESOLVER:$PORT:$WEB_ROOT:$NGINX_INCLUDE_DIR:$NGINX_TIMEOUT:$NGINX_MAX_BODY_SIZE'
envsubst "$VARS" < /etc/nginx/nginx.conf > /tmp/nginx.conf
mv /tmp/nginx.conf /etc/nginx/nginx.conf

